### ISSUE TITLE
📝 [Doc] Write A More Detailed Description What Todo To Setup A New Network

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding#19]
## 📝 Documentation Ticket

Write a more detailed description what all is todo to setup a new network.

- [x] fillin all files in the `branding`folder
- [x] copy templates `deployment/kubernetes/dns.values.template.yaml`, `deployment/kubernetes/nginx.values.template.yaml`, `deployment/kubernetes/values.template.yaml` and fill your data in
- [x] have a `templates` folder for setting up new networks. more info see comment below 👇🏼
- [x] etc.

See as well #10 .

**Comment by Tirokk** [comment]
## Vorlage (DE) – Human Connection


# Verhaltenskodex

Wir sind ein gemeinnütziges soziales Wissens- und Aktionsnetzwerk der nächsten Generation. Von Menschen – für Menschen. Open Source, fair und transparent. Für positiven lokalen und globalen Wandel in allen Lebensbereichen. Wir gestalten den öffentlichen Austausch von Wissen, Ideen und Projekten völlig neu. Unsere Funktionen bringen die Menschen zusammen – offline und online – so dass wir die Welt zu einem besseren Ort machen können.

Mit diesen Verhaltensregeln regeln wir die wesentlichen Grundsätze für das Verhalten in unserem sozialen Netzwerk. Dabei bildet die  Menschenrechtscharta der Vereinten Nationen das Herz unseres Werteverständnisses und dient uns als Orientierung. Die Verhaltensregeln dienen als Leitsätze für den persönlichen Auftritt und den Umgang untereinander. Wer als Nutzer bei uns aktiv ist, Beiträge verfasst, kommentiert oder mit anderen Nutzern, auch außerhalb des Netzwerkes, Kontakt aufnimmt, erkennt diese Verhaltensregeln als verbindlich an.

## Erwartetes Verhalten

Die folgenden Verhaltensweisen werden von allen Community-Mitgliedern erwartet und gefordert:
- Sei rücksichtsvoll und respektvoll, bei dem, was Du schreibst und tust.
- Versuche auf andere zuzugehen, bevor ein Konflikt entsteht.
- Vermeide erniedrigende, diskriminierende oder belästigende Verhaltensweisen und Ausdrücke.
- Achte Dein Umfeld und Deine Mitmenschen. Warne die Verantwortlichen der Community, falls Du eine gefährliche Situation, jemanden in Not oder Verstöße gegen diesen Verhaltenskodex bemerkst, auch wenn diese unbedeutend erscheinen.

## Nichtakzeptables Verhalten

Die folgenden Verhaltensweisen sind in unserer Community inakzeptabel:

- Diskriminierende Beiträge, Kommentare, Äußerungen oder Beleidigungen, insbesondere solche, die sich auf Geschlecht, sexuelle Orientierung, Rasse, Religion, politische oder weltanschauliche Ausrichtung oder Behinderung beziehen.
- Das Senden oder Verlinken eindeutig pornografischen Materials.
- Verherrlichung oder Verharmlosung grausamer oder unmenschlicher Gewalttätigkeiten.
- Das Veröffentlichen von personenbezogenen Daten anderer ohne deren Einverständnis oder das Androhen dessen („Doxing“)."
- Absichtliche Einschüchterung, Stalking oder Verfolgung.
- Bewerben von Produkten und Dienstleistungen mit kommerzieller Absicht.
- Strafbares Verhalten bzw. Verstoß gegen deutsches Recht.
- Befürwortung oder Ermutigung zu diesen Verhaltensweisen.

## Konsequenzen inakzeptablen Verhaltens

Wenn ein Gemeinschaftsmitglied inakzeptables Verhalten an den Tag legt, können die verantwortlichen Betreiber, Moderatoren und Administratoren des Netzwerks angemessene Maßnahmen ergreifen, u.a.:
- Aufforderung zum sofortigen Abstellen des inakzeptablen Verhaltens
- Sperren oder Löschen von Kommentaren
- Vorübergehender Ausschluss aus dem jeweiligen Beitrag
- Sperren bzw. Löschen von Inhalten
- Vorübergehender Entzug von Schreibrechten
- Vorübergehender Ausschluss aus dem Netzwerk
- Endgültiger Ausschluss aus dem Netzwerk
- Verstöße gegen deutsches Recht können zur Anzeige gebracht werden.

Wenn Du einem inakzeptablen Verhalten ausgesetzt bist, es miterlebst oder andere Bedenken hast, melde bitte so schnell wie möglich den oder die entsprechenden Inhalte an die Moderatoren.
