### ISSUE TITLE
🌟 [EPIC] Release v2.2.0-267

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding#84]
## 🌟 EPIC

Release v2.2.0-267.

### Todo

- [x] set release number
- [x] have new header logo click configuration `LOGO_HEADER_CLICK` in file `webapp/constants/logos.js`: https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5579
- [x] have `PROGRESS_BAR_COLOR_TYPE` in new `webapp/constants/donation.js`: see https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5580
- [x] added url `target` to:
  - [x] header menu
  - [x] footer menu
  - [x] donation button
